import { Item } from './item';

export const ITEMS: Item[] = [
  { id: 0, title: 'Item 0', selected: false },
  { id: 1, title: 'Item 1', selected: false },
  { id: 2, title: 'Item 2', selected: true },
  { id: 3, title: 'Item 3', selected: true },
  { id: 4, title: 'Item 4', selected: false },
  { id: 5, title: 'Item 5', selected: false },
  { id: 6, title: 'Item 6', selected: true },
  { id: 7, title: 'Item 7', selected: false },
  { id: 8, title: 'Item 8', selected: false },
  { id: 9, title: 'Item 9', selected: false },
  { id: 10, title: 'Item 10', selected: false },
  { id: 11, title: 'Item 11', selected: false },
  { id: 12, title: 'Item 12', selected: false },
  { id: 13, title: 'Item 13', selected: false },
  { id: 14, title: 'Item 14', selected: false },
  { id: 15, title: 'Item 15', selected: false },
  { id: 16, title: 'Item 16', selected: false },
  { id: 17, title: 'Item 17', selected: false },
  { id: 18, title: 'Item 18', selected: false },
  { id: 19, title: 'Item 19', selected: false },
  { id: 20, title: 'Item 20', selected: false },
  { id: 21, title: 'Item 21', selected: false },
  { id: 100, title: 'Item 100', selected: false },
  { id: 101, title: 'Item 101', selected: false },
  { id: 102, title: 'Item 102', selected: false },
  { id: 103, title: 'Item 103', selected: false },
  { id: 104, title: 'Item 104', selected: false },
  { id: 15, title: 'Item 105', selected: false },
  { id: 16, title: 'Item 106', selected: false },
  { id: 107, title: 'Item 107', selected: false },
  { id: 108, title: 'Item 108', selected: false },
  { id: 109, title: 'Item 109', selected: false },
  { id: 200, title: 'Item 200', selected: false },
  { id: 201, title: 'Item 201', selected: false },
  { id: 202, title: 'Item 202', selected: false },
  { id: 203, title: 'Item 203', selected: false },
  { id: 204, title: 'Item 204', selected: false },
];
